### ISSUE TITLE
set_TextFormatted leads to app crash

### ISSUE THREAD

**Issue by inormis** [MvvmCross/MvvmCross#1405]
### Steps to reproduce
1.  We have multiple bindings. 
2.  Raise property change for them is raised with high frequency (~50-100ms)
3.  Rotations of the device lead from time to time to app crash with exception listed below.
### Expected behavior

Device rotation doesn't lead to app crash
### Actual behavior

Application is crashed with error:

```
   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a (intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*) <0x00053>
   at Java.Interop.JniEnvironment/InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference,Java.Interop.JniObjectReference,Java.Interop.JniMethodInfo,Java.Interop.JniArgumentValue*) <0x000ab>
   at Java.Interop.JniPeerMembers/JniInstanceMethods.InvokeNonvirtualVoidMethod (string,Java.Interop.IJavaPeerable,Java.Interop.JniArgumentValue*) <0x0009f>
   at Android.Widget.TextView.set_TextFormatted (Java.Lang.ICharSequence) <0x00137>
   at Android.Widget.TextView.set_Text (string) <0x00057>
   at MvvmCross.Binding.Droid.Target.MvxTextViewTextTargetBinding.SetValueImpl (object,object) <0x00087>
   at MvvmCross.Binding.Bindings.Target.MvxConvertingTargetBinding.SetValue (object) <0x001c7>
   at MvvmCross.Binding.Bindings.MvxFullBinding/<>c__DisplayClass24_0.<UpdateTargetFromSource>b__0 () <0x000d7>
   at MvvmCross.Droid.Views.MvxAndroidMainThreadDispatcher.RequestMainThreadAction (System.Action) <0x00067>
   at MvvmCross.Binding.Bindings.MvxFullBinding.UpdateTargetFromSource (object,System.Threading.CancellationToken) <0x00193>
   at MvvmCross.Binding.Bindings.MvxFullBinding.<CreateSourceBinding>b__20_0 (object,System.EventArgs) <0x000b3>
   at MvvmCross.Binding.Bindings.SourceSteps.MvxSourceStep.SendSourcePropertyChanged () <0x0004b>
   at MvvmCross.Binding.Bindings.SourceSteps.MvxPathSourceStep.SourceBindingOnChanged (object,System.EventArgs) <0x0001b>
   at MvvmCross.Binding.Bindings.Source.MvxSourceBinding.FireChanged () <0x0004b>
   at MvvmCross.Binding.Bindings.Source.Leaf.MvxLeafPropertyInfoSourceBinding.OnBoundPropertyChanged () <0x00013>
   at MvvmCross.Binding.Bindings.Source.MvxPropertyInfoSourceBinding.SourcePropertyChanged (object,System.ComponentModel.PropertyChangedEventArgs) <0x0008f>
   at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object_object (object,intptr,intptr,intptr) <0x000f7>
```
### Configuration

**Version:** 4.2.2

**Platform:** Android

**Comment by Noires** [comment]
Could you give a bit more information about what data gets binded, to which view and when the data gets changed?
I had a similiar issue which was fixed with one of the recent changes. Look at #1379

**Comment by kjeremy** [comment]
Please make a sample reproduction with steps on github.  It turns out that layouts tend to matter in cases like these.

**Comment by kjeremy** [comment]
Please make a sample reproduction with steps on github.  It turns out that layouts tend to matter in cases like these.

**Comment by kjeremy** [comment]
Please make a sample reproduction with steps on github.  It turns out that layouts tend to matter in cases like these.

**Comment by inormis** [comment]
@Noires I've read your case carefully and I hoped update with fix will help me. Unfortunately, this bug is still reproducible (not so often though).
@kjeremy I'll try to upload a sample next Monday, cuz now I don't have access to source code

**Comment by kjeremy** [comment]
@inormis thanks.  It's the only way to fix issues like these.

**Comment by kjeremy** [comment]
@inormis Please upload a sample against the latest MvvmCross when you get the chance, Thanks!

**Comment by inormis** [comment]
@kjeremy sorry for so long delay. I've tried to reproduce it on a small sample but no luck so far. Frequent updates do not lead to app crash with the above-mentioned error in the sample. I'll keep trying to reproduce it.

**Comment by kjeremy** [comment]
It's most likely do to your specific layout or fragments or something.  For
instance I used to see this but only in a `MvxRecyclerView`.  Try to make
your repro use as similar a UI as your other app.

**Comment by inormis** [comment]
@kjeremy I used MvxRecyclerView in the sample. I'll try to make it similar to main app.

**Comment by Noires** [comment]
I had really rarely these crashes with my SearchView and the binding with the Query-Property. Unsure if that was just a sideeffect of the MvxRecyclerView, but better pointing it out here, just remembered again.

```
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) object.wrapper_native_0xb4ecb6f9 (intptr,intptr,intptr,Android.Runtime.JValue*) <IL 0x0002a, 0xffffffff>
  at (wrapper delegate-invoke) <Module>.invoke_void_intptr_intptr_intptr_JValue* (intptr,intptr,intptr,Android.Runtime.JValue*) <IL 0x0007d, 0xffffffff>
  at Android.Runtime.JNIEnv.CallVoidMethod (intptr,intptr,Android.Runtime.JValue*) [0x00040] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:567
  at Android.Widget.TextView.set_TextFormatted (Java.Lang.ICharSequence) [0x0004b] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Widget.TextView.cs:3237
  at Android.Widget.TextView.set_Text (string) [0x00013] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Widget.TextView.cs:3248
  at MvvmCross.Binding.Droid.Target.MvxTextViewTextTargetBinding.SetValueImpl (object,object) <IL 0x0000c, 0x000ab>
  at MvvmCross.Binding.Bindings.Target.MvxConvertingTargetBinding.SetValue (object) [0x00088] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Target\MvxConvertingTargetBinding.cs:61
  at MvvmCross.Binding.Bindings.MvxFullBinding.UpdateTargetFromSource (object) [0x00024] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\MvxFullBinding.cs:156
  at MvvmCross.Binding.Bindings.MvxFullBinding.<CreateSourceBinding>b__15_0 (object,System.EventArgs) [0x0000c] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\MvxFullBinding.cs:85
  at MvvmCross.Binding.Bindings.SourceSteps.MvxSourceStep.SendSourcePropertyChanged () [0x00006] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxSourceStep.cs:119
  at MvvmCross.Binding.Bindings.SourceSteps.MvxCombinerSourceStep.SubStepOnChanged (object,System.EventArgs) [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxCombinerSourceStep.cs:107
  at MvvmCross.Binding.Bindings.SourceSteps.MvxSourceStep.SendSourcePropertyChanged () [0x00006] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxSourceStep.cs:119
  at MvvmCross.Binding.Bindings.SourceSteps.MvxCombinerSourceStep.SubStepOnChanged (object,System.EventArgs) [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxCombinerSourceStep.cs:107
  at MvvmCross.Binding.Bindings.SourceSteps.MvxSourceStep.SendSourcePropertyChanged () [0x00006] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxSourceStep.cs:119
  at MvvmCross.Binding.Bindings.SourceSteps.MvxCombinerSourceStep.SubStepOnChanged (object,System.EventArgs) [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxCombinerSourceStep.cs:107
  at MvvmCross.Binding.Bindings.SourceSteps.MvxSourceStep.SendSourcePropertyChanged () [0x00006] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxSourceStep.cs:119
  at MvvmCross.Binding.Bindings.SourceSteps.MvxPathSourceStep.SourceBindingOnChanged (object,System.EventArgs) [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxPathSourceStep.cs:71
  at MvvmCross.Binding.Bindings.Source.MvxSourceBinding.FireChanged () [0x00006] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Source\MvxSourceBinding.cs:36
  at MvvmCross.Binding.Bindings.Source.Leaf.MvxLeafPropertyInfoSourceBinding.OnBoundPropertyChanged () [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Source\Leaf\MvxLeafPropertyInfoSourceBinding.cs:29
  at MvvmCross.Binding.Bindings.Source.MvxPropertyInfoSourceBinding.SourcePropertyChanged (object,System.ComponentModel.PropertyChangedEventArgs) [0x00020] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Source\MvxPropertyInfoSourceBinding.cs:88
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object_object (object,intptr,intptr,intptr) <IL 0x00062, 0xffffffff>
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) <IL 0x00034, 0xffffffff>
  at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) [0x00038] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:295
  at System.Reflection.MethodBase.Invoke (object,object[]) [0x00000] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/reflection/methodbase.cs:277
  at MvvmCross.Platform.WeakSubscription.MvxWeakEventSubscription`2<TKey_REF, TValue_REF>.OnSourceEvent (object,TValue_REF) [0x0000f] in D:\git\MvvmCross\MvvmCross\Platform\Platform\WeakSubscription\MvxWeakEventSubscription.cs:75
  at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs) <IL 0x00074, 0xffffffff>
  at MvvmCross.Core.ViewModels.MvxNotifyPropertyChanged/<>c__DisplayClass10_0.<RaisePropertyChanged>b__0 () <IL 0x0001c, 0x000a7>
  at MvvmCross.Droid.Views.MvxAndroidMainThreadDispatcher.RequestMainThreadAction (System.Action) <IL 0x0001f, 0x00133>
  at MvvmCross.Platform.Core.MvxMainThreadDispatchingObject.InvokeOnMainThread (System.Action) [0x00000] in D:\git\MvvmCross\MvvmCross\Platform\Platform\Core\MvxMainThreadDispatchingObject.cs:18
  at MvvmCross.Core.ViewModels.MvxNotifyPropertyChanged.RaisePropertyChanged (System.ComponentModel.PropertyChangedEventArgs) <IL 0x00044, 0x00277>
  at MvvmCross.Core.ViewModels.MvxNotifyPropertyChanged.RaisePropertyChanged (string) <IL 0x00009, 0x000b3>
  at MvvmCross.Core.ViewModels.MvxNotifyPropertyChanged.SetProperty<int> (int&,int,string) <IL 0x00023, 0x00147>
  at XCPCore.Models.BaseCategory.set_Count (int) [0x00001] in w:\DevWA\MobileXCP~BARONDST\MobileXCP\MobileXcp\MobileXcp.XcpCore\Models\BaseCategory.cs:36
  at XCPCore.ViewModels.Meas.ConfigInViewModel.updateChannels () [0x00149] in w:\DevWA\MobileXCP~BARONDST\MobileXCP\MobileXcp\MobileXcp.XcpCore\ViewModels\Meas\ConfigInViewModel.cs:209
  at XCPCore.ViewModels.Meas.ConfigInViewModel.set_SearchString (string) [0x00043] in w:\DevWA\MobileXCP~BARONDST\MobileXCP\MobileXcp\MobileXcp.XcpCore\ViewModels\Meas\ConfigInViewModel.cs:158
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object (object,intptr,intptr,intptr) <IL 0x0005a, 0xffffffff>
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) <IL 0x00034, 0xffffffff>
  at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) [0x00038] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:295
  at System.Reflection.MonoProperty.SetValue (object,object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) [0x0006a] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/mcs/class/corlib/System.Reflection/MonoProperty.cs:445
  at System.Reflection.PropertyInfo.SetValue (object,object,object[]) [0x00000] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/mcs/class/corlib/System.Reflection/PropertyInfo.cs:111
  at MvvmCross.Binding.Bindings.Source.Leaf.MvxLeafPropertyInfoSourceBinding.SetValue (object) [0x00060] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Source\Leaf\MvxLeafPropertyInfoSourceBinding.cs:83
  at MvvmCross.Binding.Bindings.SourceSteps.MvxPathSourceStep.SetSourceValue (object) [0x0001b] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxPathSourceStep.cs:85
  at MvvmCross.Binding.Bindings.SourceSteps.MvxSourceStep.SetValue (object) [0x0001a] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxSourceStep.cs:70
  at MvvmCross.Binding.Bindings.MvxFullBinding.UpdateSourceFromTarget (object) [0x00013] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\MvxFullBinding.cs:179
  at MvvmCross.Binding.Bindings.MvxFullBinding.<CreateTargetBinding>b__18_0 (object,MvvmCross.Binding.Bindings.Target.MvxTargetChangedEventArgs) [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\MvxFullBinding.cs:140
  at MvvmCross.Binding.Bindings.Target.MvxTargetBinding.FireValueChanged (object) [0x00006] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Target\MvxTargetBinding.cs:32
  at MvvmCross.Binding.Bindings.Target.MvxConvertingTargetBinding.FireValueChanged (object) [0x0003f] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Target\MvxConvertingTargetBinding.cs:93
  at MvvmCross.Binding.Droid.Target.MvxSearchViewQueryTextTargetBinding.HandleQueryTextChanged (object,Android.Widget.SearchView/QueryTextChangeEventArgs) <IL 0x00019, 0x0014f>
  at Android.Widget.SearchView/IOnQueryTextListenerImplementor.OnQueryTextChange (string) [0x00017] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Widget.SearchView.cs:322
  at Android.Widget.SearchView/IOnQueryTextListenerInvoker.n_OnQueryTextChange_Ljava_lang_String_ (intptr,intptr,intptr) [0x00011] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Widget.SearchView.cs:207
  at (wrapper dynamic-method) object.bf5df6e6-8c4e-4c9b-b90b-f3b9d377de80 (intptr,intptr,intptr) <IL 0x00017, 0x0004b>
  at (wrapper native-to-managed) object.bf5df6e6-8c4e-4c9b-b90b-f3b9d377de80 (intptr,intptr,intptr) <IL 0x00029, 0xffffffff>

Attempting native Android stacktrace:

 at ???+0 [0x6fe827f8]
 at ???+0 [0x3f7ffffc]

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
06-02 12:24:13.942 E/mono-rt ( 6344):
```

**Comment by inormis** [comment]
@kjeremy may I ask you to send the sample privately? I have reasons not to publish it publicly.

**Comment by inormis** [comment]
@kjeremy I've cut our main project and it's possible now to reproduce the exception while rotating the device.

**Comment by kjeremy** [comment]
@inormis yes.  I think you can send it to me over the slack channel.  Or google drive or something.

**Comment by inormis** [comment]
@kjeremy getsync is ok?

**Comment by inormis** [comment]
Let me know when you've downloaded it

> https://drive.google.com/file/d/0B3d_T4nYNpJ8TDNPamlLWGc5SUk/view?usp=sharing

**Comment by kjeremy** [comment]
Done.  If I don't get to it today I will try to look monday.

**Comment by inormis** [comment]
@kjeremy no problem. 
Steps to reproduce: 
- start application
- rotate device multiple times.
- usually, it takes 10-20 rotations. 

Better to run it in debug mode.  In the sample, it doesn't crash app for some reason but I can see it in the output.

**Comment by kjeremy** [comment]
Thanks, I can reproduce it.  I'm debating if in addition to the `null` checks whether we should also check if our views' `Handle == IntPtr.Zero` in all of these target bindings as a precaution against this sort of thing.

**Comment by inormis** [comment]
Does this problem is related to the bug reported by Noires and fixed in 4.2.2?

**Comment by kjeremy** [comment]
#1379?  Probably.  Maybe I fixed one case there but not the one we're hitting here.  Maybe we need to call `ClearAllBindings()` in some other case.  Also in your original report you said that you couldn't reproduce it when rotating the device (I do not know what your original reproduction steps were) but now you can.

**Comment by inormis** [comment]
In the original report, I've said that 

> Rotations of the device lead from time to time to app crash with exception listed below

In the new sample I couldn't reproduce it, but in the second sample (what was cut from our main project) it can be easily reproduced.

**Comment by kjeremy** [comment]
@inormis Figured it out. You aren't taking advantage of the fix in #1379.  If you look at https://github.com/MvvmCross/MvvmCross-AndroidSupport/pull/273 you will see that we keep track of ViewHolders created by the `MvxRecyclerAdapter`.  All `IMvxRecyclerViewHolder`s are added to this list which is then cleared out by `ClearAllBindings()` when the `MvxRecyclerView` is attached.  Clearly I didn't make this accessible enough because I forgot that people can overload `OnCreateViewHolder()`.

So as a workaround add the following to `DecoratedRecyclerViewAdapter`:

```
private readonly List<WeakReference<IMvxRecyclerViewHolder>> _viewHolders = new List<WeakReference<IMvxRecyclerViewHolder>>();
```

```
public override RecyclerView.ViewHolder OnCreateViewHolder(ViewGroup parent, int viewType)
{
    // .... your existing code ...
    _viewHolders.Add(new WeakReference<IMvxRecyclerViewHolder>(holder));
    return holder;
}

public override void ClearAllBindings()
        {
            base.ClearAllBindings();

            foreach (var vhRef in _viewHolders)
            {
                IMvxRecyclerViewHolder vh;
                if (vhRef.TryGetTarget(out vh))
                    vh.ClearAllBindings();
            }

            _viewHolders.Clear();
        }
```

**Comment by inormis** [comment]
@kjeremy thanks a lot. So far so good. 
Will it be somehow managed by mvvmcros in the future?

**Comment by kjeremy** [comment]
I'm going through our bindings and making all of the events
WeakSubscriptions.  I think that might take care of the issue in the
adapter.

**Comment by kjeremy** [comment]
Haven't forgotten about this.  Trying to figure out the best solution that is not a hack.

**Comment by inormis** [comment]
Here is the project https://github.com/inormis/MvxSIGSEVTest where it can be still reproduced. Go next view and back for ~ 7 times and app crashes with stacktrace listed bellow.

`  at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a (intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*) <0x00012>
  at Java.Interop.JniEnvironment/InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference,Java.Interop.JniObjectReference,Java.Interop.JniMethodInfo,Java.Interop.JniArgumentValue*) [0x0008f] in /Users/builder/data/lanes/3511/ce955cc0/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12079
  at Java.Interop.JniPeerMembers/JniInstanceMethods.InvokeNonvirtualVoidMethod (string,Java.Interop.IJavaPeerable,Java.Interop.JniArgumentValue*) [0x00022] in /Users/builder/data/lanes/3511/ce955cc0/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:41
  at Android.Widget.TextView.set_TextFormatted (Java.Lang.ICharSequence) [0x0001e] in /Users/builder/data/lanes/3511/ce955cc0/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Widget.TextView.cs:2844
  at Android.Widget.TextView.set_Text (string) [0x00013] in /Users/builder/data/lanes/3511/ce955cc0/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Widget.TextView.cs:2855
  at MvvmCross.Binding.Droid.Target.MvxTextViewTextTargetBinding.SetValueImpl (object,object) <IL 0x0000c, 0x0007b>
  at MvvmCross.Binding.Bindings.Target.MvxConvertingTargetBinding.SetValue (object) [0x00093] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Target\MvxConvertingTargetBinding.cs:64
  at MvvmCross.Binding.Bindings.MvxFullBinding/<>c__DisplayClass24_0.<UpdateTargetFromSource>b__0 () [0x00025] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\MvxFullBinding.cs:182
  at MvvmCross.Droid.Views.MvxAndroidMainThreadDispatcher.RequestMainThreadAction (System.Action) <IL 0x0001f, 0x00102>
  at MvvmCross.Binding.Bindings.MvxFullBinding.UpdateTargetFromSource (object,System.Threading.CancellationToken) [0x0004f] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\MvxFullBinding.cs:173
  at MvvmCross.Binding.Bindings.MvxFullBinding.<CreateSourceBinding>b__20_0 (object,System.EventArgs) [0x00018] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\MvxFullBinding.cs:99
  at MvvmCross.Binding.Bindings.SourceSteps.MvxSourceStep.SendSourcePropertyChanged () [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxSourceStep.cs:117
  at MvvmCross.Binding.Bindings.SourceSteps.MvxCombinerSourceStep.SubStepOnChanged (object,System.EventArgs) [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxCombinerSourceStep.cs:107
  at MvvmCross.Binding.Bindings.SourceSteps.MvxSourceStep.SendSourcePropertyChanged () [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxSourceStep.cs:117
  at MvvmCross.Binding.Bindings.SourceSteps.MvxPathSourceStep.SourceBindingOnChanged (object,System.EventArgs) [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\SourceSteps\MvxPathSourceStep.cs:73
  at MvvmCross.Binding.Bindings.Source.MvxSourceBinding.FireChanged () [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Source\MvxSourceBinding.cs:35
  at MvvmCross.Binding.Bindings.Source.Leaf.MvxLeafPropertyInfoSourceBinding.OnBoundPropertyChanged () [0x00000] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Source\Leaf\MvxLeafPropertyInfoSourceBinding.cs:29
  at MvvmCross.Binding.Bindings.Source.MvxPropertyInfoSourceBinding.SourcePropertyChanged (object,System.ComponentModel.PropertyChangedEventArgs) [0x00020] in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Source\MvxPropertyInfoSourceBinding.cs:88
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object_object (object,intptr,intptr,intptr) <IL 0x0005b, 0x00113>
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) <0x00012>
  at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) [0x00038] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:305
  at System.Reflection.MethodBase.Invoke (object,object[]) [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/reflection/methodbase.cs:229
  at MvvmCross.Platform.WeakSubscription.MvxWeakEventSubscription`2<TSource_REF, TEventArgs_REF>.OnSourceEvent (object,TEventArgs_REF) [0x0000a] in D:\git\MvvmCross\MvvmCross\Platform\Platform\WeakSubscription\MvxWeakEventSubscription.cs:77
  at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs) <IL 0x00073, 0x00123>
  at MvvmCross.Core.ViewModels.MvxNotifyPropertyChanged/<>c__DisplayClass10_0.<RaisePropertyChanged>b__0 () <IL 0x0001c, 0x000a0>
  at MvvmCross.Droid.Views.MvxAndroidMainThreadDispatcher.RequestMainThreadAction (System.Action) <IL 0x0001f, 0x00102>
  at MvvmCross.Platform.Core.MvxMainThreadDispatchingObject.InvokeOnMainThread (System.Action) [0x00000] in D:\git\MvvmCross\MvvmCross\Platform\Platform\Core\MvxMainThreadDispatchingObject.cs:18
  at MvvmCross.Core.ViewModels.MvxNotifyPropertyChanged.RaisePropertyChanged (System.ComponentModel.PropertyChangedEventArgs) <IL 0x00044, 0x00223>
  at MvvmCross.Core.ViewModels.MvxNotifyPropertyChanged.RaisePropertyChanged (string) <IL 0x00009, 0x0008d>
  at MvxSIGSEVTest.Droid.Core.Models.ListItem.set_Count (int) [0x00008] in C:\Projects\MvxSIGSEVTest\MvxSIGSEVTest\MvxSIGSEVTest.Droid\Core\Models\ListItem.cs:21
  at MvxSIGSEVTest.Droid.Core.Services.ListService.<OnTick>b__5_0 () [0x00017] in C:\Projects\MvxSIGSEVTest\MvxSIGSEVTest\MvxSIGSEVTest.Droid\Core\Services\ListService.cs:31`

**Comment by SeeD-Seifer** [comment]
The only idea I have is to add protection into binding setter for Android branch.

The crash happens from the `MvxTextViewTextTargetBinding` class.
I would try to update `SetValueImpl` method so that it look like this:

```
protected override void SetValueImpl(object target, object toSet)
{
    var textView = (TextView)target;
    if (textView != null && textView.Handle != IntPtr.Zero)
    {
         textView.Text = (string)toSet;
    }
}
```

Even it could decrease crash-rate dramatically, it won't disappear completely.
If it works, it make sense to introduce the same protection into all Android bindings.

**Comment by kjeremy** [comment]
It already does that check before calling SetValue.

**Comment by kjeremy** [comment]
I cannot reproduce this with https://github.com/inormis/MvxSIGSEVTest on my Nexus 6P or my API 24 emulator image with latest Xamarin Stable and MvvmCross 4.4.0 in either debug or release.

**Comment by inormis** [comment]
mhm, it reproduces on Api 17 and 21 emulator images constantly. On my physical device HomTom 7 Pro too. Try to decrease timer interval in ListService may be it will help.

![image](https://cloud.githubusercontent.com/assets/2038932/20973077/e2777b04-bc9f-11e6-9bfe-6c04d9a853ed.png)

**Comment by Cheesebaron** [comment]
Nexus 5X, API 23 can reproduce this too.

**Comment by kjeremy** [comment]
Damn you @Cheesebaron.  I'll try with a lower API level.

**Comment by kjeremy** [comment]
I can reproduce this on API21 but not 24+ on either VM or device (no idea why).  I've also switched back to `MvxBindingContext` which rules out any of the threading issues we've seen with `MvxTaskBasedBindingContext`.

By setting `MvxBindingTrace.TraceBindingLevel = MvxTraceLevel.Diagnostic` and implementing `CreateDebugTrace` I can see that every time we come back to the first fragment we end up with one more event handler on the `MvxRecyclerView` bindings (I've removed the call to `Update` in `UserVisibleHint` because it's extraneous and also added a binding to a `TextView` which behaves as it should).  Note that without `UserVisibleHint` we are refreshing the values twice when navigating back: once with the previous values when we create the view and the next time in `RecyclerViewTestViewModel.Update` called from `OnViewCreated`

**Comment by kjeremy** [comment]
Once I can use the xamarin profiler I should at least be able to see what's going on in terms of roots.

**Comment by inormis** [comment]
Is there any workaround for that, until final fix will be released? I've tried to  wrap raising of PropertyChange events in try catch block but it doesn't help.

**Comment by kjeremy** [comment]
There's a workaround:  If you override `MvxRecyclerView` and call `SetAdapter(null)` in `OnDetachedFromWindow()` you won't crash.  This may present problems with nested `RecyclerView`'s or possible if you are in a `ViewPager` but I don't know for sure.

**Comment by inormis** [comment]
Will it be released before 5.0?

**Comment by Cheesebaron** [comment]
You can grab latest develop build from the MyGet feed: https://www.myget.org/F/mvvmcross/api/v2

**Comment by ilyaspotware** [comment]
When will the 5th version be available? I have issues upgrading to 4.5devbuild.

**Comment by Cheesebaron** [comment]
@ilyaspotware If you want a faster release, join in and make some PRs. If installing 4.5 from MyGet does not work for you, please create an issue with details so we can fix it.

**Comment by Noires** [comment]
Its weird, i havent had issues on the 4.2.2 release but since i updated now to the latest release 4.4.0. The error started to appear again and that reproducable in my company app on just one rotation during a measurement, which normally worked fine even with the error being there at the start. 

Is there something i missed or something i have to adjust?

**Comment by kjeremy** [comment]
@Noires do you have a recyclerview?  Please try the latest packages on myget.  You can also make your own recyclerview inheriting from the mvx one and override `OnDetachedFromWindow`

**Comment by Noires** [comment]
@kjeremy thanks, i will try it out!

**Comment by inormis** [comment]
I've tried to override OnDetachedFromWindow and add next code 
`GetLayoutManager()?.RemoveAllViews();`
but it's still reproducible. I'll try to update MVVMCross from https://www.myget.org/F/mvvmcross/api/v2. May be it will help.

**Comment by inormis** [comment]
If it won't work, then I'll add sources our solution and will try to investigate the issue.

**Comment by Cheesebaron** [comment]
If you are using the nugets from MyGet, you could try enabling fetching symbols from symbol servers. The PDB files are patched so they look for sources in our GitHub repositories via GitLink. Hopefully that works in Visual Studio.

**Comment by inormis** [comment]
@Cheesebaron, have I understood right that I need an additional URL for symbols? (according to http://docs.myget.org/docs/reference/symbols#Consuming_symbol_packages_in_Visual_Studio) 
As far as I've understood I ned to authenticated to get those symbols or to get an URL with a token.

**Comment by Cheesebaron** [comment]
See the readme for GitLink to set it up:

https://github.com/GitTools/GitLink

You should be able to just do:

![ss](https://github.com/GitTools/GitLink/raw/develop/doc/images/visualstudio_enablesourceserversupport.png)

That should pick up the symbols from the patched pdb files that are in the NuGet.

**Comment by inormis** [comment]
By the way, 4.5 didn't help.
After some time I start to get warnings 

> Weak Target has been GCed by Android AppCompatTextView

And 2-4 minutes later application crashes without any information in output. Therefore I'd like to debug the  MVVMCross to get more details about the root cause.

**Comment by inormis** [comment]
@Cheesebaron  thank you. Works like a charm

**Comment by kjeremy** [comment]
Are you using a different project to test this? Can you put it on GitHub so
I can try and debug the issue. This issue was really about the recycler
view. Does your reproduction have one?

On Feb 16, 2017 7:13 AM, "Artiom K" <notifications@github.com> wrote:

@Cheesebaron <https://github.com/Cheesebaron> thank you. Works like a charm

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MvvmCross/MvvmCross/issues/1405#issuecomment-280314908>,
or mute the thread

**Comment by inormis** [comment]
I use our production project.  What I have so far:

After several switching between fragments, I start to get 
> Weak Target has been GCed by Android AppCompatTextView

After enabling **Enable source server support** I could figure out where it comes from. In simple words the app works like this:
There're two Fragments:
- PersonListFragment with PersonListViewModel (SingleInstance)
- CreateNewPersonFragment with CreateNewPersonViewModel (Instance per dependency)

Moving to **CreateNewPersonFragment** creates a new **CreateNewPersonViewModel** (it does some calculations and constantly raises PropertyChanged event).
But moving back to PersonListFragment doesn't lead to call of **CreateNewPersonFragment.OnDestroy.** Therefore Dispose of **CreateNewPersonViewModel** is not called and we continue to raise PropertyChanged events. 
Now I want to figure out the right way of disposing of **CreateNewPersonViewModel**.

**Comment by kjeremy** [comment]
Right.  Does `OnDestroyView` get called?  Typically when dealing with
fragments I have to use that instead of `OnDestroy`.

**Comment by inormis** [comment]
Yep, you are right. I have moved disposing of viewmodel to OnDistroyView and now it works as expected.  
(I still get error with set_ErrorFormatted, but this would be another investigation).

So far:  warning doesn't appear anymore and app doesn't crash. Thank you very much guys for the help!

**Comment by inormis** [comment]
Is it possible to get pdb for 4.4.0? In some scenarios, I continue to get warnings. Something is not destroyed properly on our side.  
P.S. I home one-day Xamarin Profiler will work properly)

**Comment by Cheesebaron** [comment]
pdb files for 4.4.0 are on symbolsource.org

**Comment by inormis** [comment]
I've added next symbol servers
- http://srv.symbolsource.org/pdb/Public
- http://srv.symbolsource.org/pdb/MyGet

and done following steps
- Uncheck “Enable Just My Code (Managed only)”.
- Uncheck “Enable .NET Framework source stepping”
- Check “Enable source server support”.
- Uncheck “Require source files to exactly match the original version”

But I get in output:

> PdbNavigator: Downloader: http://srv.symbolsource.org/pdb/Public::MvvmCross.Binding.dll::B3BD0A6D3F514AE6A01E688F5054E8D31 -> NotFound
PdbNavigator: Downloader: http://srv.symbolsource.org/pdb/Public::MvvmCross.Binding.dll::B3BD0A6D3F514AE6A01E688F5054E8D31 -> NotFound 
PdbNavigator: Downloader: http://srv.symbolsource.org/pdb/MyGet::MvvmCross.Binding.dll::B3BD0A6D3F514AE6A01E688F5054E8D31 -> NotFound


What am I missing?

**Comment by Cheesebaron** [comment]
Not sure why it cannot find the symbols, I have been pushing them for every release through NuGet.

**Comment by inormis** [comment]
I've figured out, that in our custom controls we didn't clear bindings in OnDetachedFromWindow. This in conjunction with MemoryLeaks in our ViewModels led to such warnings and app crash.

**Comment by evgenyvalavin** [comment]
@inormis does it mean PR #1536 needs to be reverted to get rid of the side effect?

> I've figured out, that in our custom controls we didn't clear bindings in OnDetachedFromWindow. This in conjunction with MemoryLeaks in our ViewModels led to such warnings and app crash.

**Comment by evgenyvalavin** [comment]
> @inormis does it mean PR #1536 needs to be reverted to get rid of the side effect?
> 
> > I've figured out, that in our custom controls we didn't clear bindings in OnDetachedFromWindow. This in conjunction with MemoryLeaks in our ViewModels led to such warnings and app crash.

@Cheesebaron any thoughts on this? The side effect affects UX really hard

**Comment by Cheesebaron** [comment]
@evgenyvalavin any thoughts on what specifically?
