### ISSUE TITLE
UWP MvxSuspensionManager does not call ReloadState nor ReloadFromBundle after migration to mvvmcross 5.4

### ISSUE THREAD

**Issue by symibsoft** [MvvmCross/MvvmCross#2388]
### Steps to reproduce :scroll:

1.Create an UWP APP

2.Manage the suspension Manager in the onlaunched method:

            Frame rootFrame = Window.Current.Content as Frame;

            if (rootFrame == null)
            {
                rootFrame = new Frame();

                rootFrame.CacheSize = 10;

                if (e.PreviousExecutionState == ApplicationExecutionState.Terminated)
                {
                    // Restore the saved session state only when appropriate
                    try
                    {
                        var setup = new Setup(rootFrame);
                        setup.Initialize();
                        //setup.EnsureInitialized(typeof(IMvxSuspensionManager));

                        RegisterSingletonsInterfaces();

                        var DeviceInformation = Mvx.GetSingleton<IDeviceInformationHelper>();
                        LocalCacheContainer.Load(DeviceInformation.GetDatabasePath(), false);

                        var suspension = Mvx.GetSingleton<IMvxSuspensionManager>() as MvxSuspensionManager;

                        await suspension.RestoreAsync();

                    }
                    catch (Exception ex)
                    {
                        if (System.Diagnostics.Debugger.IsAttached)
                            System.Diagnostics.Debugger.Break();
                    }
                }

                // Place the frame in the current Window
                Window.Current.Content = rootFrame;
            }
            if (e.PrelaunchActivated == false)
            {
                if (rootFrame.Content == null)
                {
                    var setup = new Setup(rootFrame);
                    setup.Initialize();

                    RegisterSingletonsInterfaces();

                    var start = Mvx.Resolve<IMvxAppStart>();

                    Settings.IsDeveloperModeActive = false;
                    start.Start();

                }

                // Ensure the current window is active
                Window.Current.Activate();                
            }

3. Manage the save async in the onsuspending method

            var deferral = e.SuspendingOperation.GetDeferral();

            var suspension = Mvx.GetSingleton<IMvxSuspensionManager>() as MvxSuspensionManager;

            await suspension.SaveAsync();

            deferral.Complete();

### Expected behavior :thinking:
ReloadState or ReloadFromBundle method called in last viewmodel

### Actual behavior :bug:
The navigation is restored successfully but no method in the viewmodel called.

### Configuration :wrench:

**Version:** 5.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
This should be fixed by #2359, but you still might need to modify some code if you're using the MvxNavigationService. There will be docs on what needs to be done and also a dedicated section on the release notes.

We should leave this issue one open until you can verify the issue is solved.

**Comment by symibsoft** [comment]
If I understand your answer this bug will be fixed in the 5.5 version, is it correct?

If yes, when this version will be released? Can I have a workaround now?

Thanks

**Comment by nmilcoff** [comment]
Yes, that's right. Unfortunately there's no workaround as the issue wasn't super easy to solve.

But you can use the MyGet packages which are based on latest `develop`.

**Comment by symibsoft** [comment]
Hi guys, I have updated to the last 5.5.2 version but this issue is still present.
