### ISSUE TITLE
Failed to resolve type MvvmCross.ViewModels.IMvxAppStart

### ISSUE THREAD

**Issue by haohighview** [MvvmCross/MvvmCross#2810]
### Steps to reproduce :scroll:
```
Xamarin caused by: android.runtime.JavaProxyThrowable: MvvmCross.Exceptions.MvxIoCResolveException: Failed to resolve type MvvmCross.ViewModels.IMvxAppStart
MvvmCross.IoC.MvxIoCContainer.Resolve(Type t)<a1ab21c493b64a15919bccd6a6fb7be2>:0
MvvmCross.IoC.MvxIoCContainer.Resolve<T>()<a1ab21c493b64a15919bccd6a6fb7be2>:0
MvvmCross.IoC.MvxIoCProvider.Resolve<T>()<a1ab21c493b64a15919bccd6a6fb7be2>:0
MvvmCross.Mvx.Resolve<TService>()<a1ab21c493b64a15919bccd6a6fb7be2>:0
MvvmCross.Platforms.Android.Views.MvxActivityViewExtensions.OnViewDestroy(IMvxAndroidView androidView)<a1ab21c493b64a15919bccd6a6fb7be2>:0
MvvmCross.Platforms.Android.Views.MvxActivityAdapter.EventSourceOnDestroyCalled(object sender, EventArgs eventArgs)<a1ab21c493b64a15919bccd6a6fb7be2>:0
at (wrapper delegate-invoke) <Module>.invoke_void_object_EventArgs(object,System.EventArgs)
MvvmCross.Base.MvxDelegateExtensions.Raise(EventHandler eventHandler, object sender)<a1ab21c493b64a15919bccd6a6fb7be2>:0
MvvmCross.Droid.Support.V7.AppCompat.EventSource.MvxEventSourceAppCompatActivity.OnDestroy()<a463012b56d64d1f9cc54a527e8dd780>:0
MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatActivity.OnDestroy()<a463012b56d64d1f9cc54a527e8dd780>:0
Android.App.Activity.n_OnDestroy(IntPtr jnienv, IntPtr native__this)<8e97598d39014e64a9b297bda6092daf>:0
at (wrapper dynamic-method) System.Object.51564007-77ee-4aca-b000-e0c439692f3c(intptr,intptr)
mvvmcross.droid.support.v7.appcompat.MvxAppCompatActivity.n_onDestroy(Native Method)
mvvmcross.droid.support.v7.appcompat.MvxAppCompatActivity.onDestroy()MvxAppCompatActivity.java:61
android.app.Activity.performDestroy()Activity.java:7462
android.app.Instrumentation.callActivityOnDestroy()Instrumentation.java:1255
android.app.ActivityThread.performDestroyActivity()ActivityThread.java:4590
android.app.ActivityThread.handleDestroyActivity()ActivityThread.java:4621
android.app.ActivityThread.-wrap5()Unknown Source:0
android.app.ActivityThread$H.handleMessage()ActivityThread.java:1757
android.os.Handler.dispatchMessage()Handler.java:105
android.os.Looper.loop()Looper.java:164
android.app.ActivityThread.main()ActivityThread.java:6938
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.Zygote$MethodAndArgsCaller.run()Zygote.java:327
com.android.internal.os.ZygoteInit.main()ZygoteInit.java:1374

 public SplashScreen() : base(Resource.Layout.SplashScreen)
 {
        this.RegisterSetupType<Setup>();
 }

 protected override void RunAppStart(Bundle bundle)
 {
        var starter = MvvmCross.Mvx.Resolve<IMvxAppStart>();
        starter.Start(model);
  }
```

### Configuration :wrench:

**Version:** 
MvvmCross 6.0.0

**Platform:** 
Android 5.1.1, 8.0.0
SAMSUNG SM-G5500
SAMSUNG SM-G950F

**Comment by nickrandolph** [comment]
Hi, can you provide more info on how your application is setup. Are you registering your first view model in you App class?

Alternatively, can you reproduce this in the Playground sample apps?

**Comment by nickrandolph** [comment]
@haohighview can you please follow up with more information so we can resolve this issue?

**Comment by haohighview** [comment]
Sorry, I can't reproduce the bug. the bug information comes from hockeyapp.

 public class Setup : MvxAppCompatSetup
    {   
        public override MvxLogProviderType GetDefaultLogProviderType()
        {
            return MvxLogProviderType.Serilog;
        }

        protected override IMvxApplication CreateApp()
        {
            return new App();
        }

        protected override IMvxLogProvider CreateLogProvider()
        {
            Log.Logger = new LoggerConfiguration().MinimumLevel.Debug().WriteTo.AndroidLog().CreateLogger();
            return base.CreateLogProvider();
        }

        protected override IMvxAndroidViewPresenter CreateViewPresenter()
        {
            return new MvxAppCompatViewPresenter(AndroidViewAssemblies);
        }

        protected override void InitializePlatformServices()
        {
            base.InitializePlatformServices();
            Mvx.RegisterSingleton<IPlatformService>(new AndroidPlatformService());
        }
    }

**Comment by nickrandolph** [comment]
@haohighview can you try overriding the OnDestroy in your activity that inherits from MvxAppCompatActivity and wrapping the call to the base method in a try catch.
Are you seeing this issue being reported a lot in HockeyApp, or was this a one off?
The only thing I can think of is that the user terminated the app before MvxSetup got a chance to be registered (eg they launched, then immediately closed the app)

**Comment by nickrandolph** [comment]
@haohighview did you have any luck with this?

**Comment by haohighview** [comment]
now, I can reproduce the bug. When the user just opened the app and is on the splash page, then click on the phone home button.

I overrode the OnDestroy  and call to the base method in a try catch. Now I get another error.
android.util.SuperNotCalledException: Activity {com.boundlss.aisandroid/appboundlss.droid.SplashScreen} did not call through to super.onDestroy()
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4262)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4291)
	at android.app.ActivityThread.-wrap7(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5975)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by haohighview** [comment]
@nickrandolph Do you have any update or need of further information?

**Comment by haohighview** [comment]
I created a sample but can't reproduce the issue.

**Comment by nickrandolph** [comment]
Does this happen if you launch the app, and then press back button before the mainactivity has had a chance to display. I think what's happening is that it's attempting to destroy either the splash or mainactivity before the CurrentActivity has been correctly setup, thus causing this exception

**Comment by haohighview** [comment]
yes, it happened launch the app, and then press back/home button before the mainactivity display

**Comment by nmilcoff** [comment]
If that is the case @nickrandolph that means IMvxAppStart is not registered yet, right? Then there is technically no reason to call `ResetStart()` I guess.

So could the issue be solved by replacing `Resolve` for `TryResolve` [here](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Platforms/Android/Views/MvxActivityViewExtensions.cs#L79)?

**Comment by nickrandolph** [comment]
Yes, I think that should be sufficient to resolve this issue.
@haohighview would you be kind enough to raise a PR based on the suggestion made by @nmilcoff

**Comment by nickrandolph** [comment]
@haohighview did you get around to raising a PR? If so, can you update it to reference this issue

**Comment by CMorooney** [comment]
I'll try and submit a PR later for this

**Comment by stefan89** [comment]
I still encounter the same issue with MvvmCross version 6.2.0.

The crash occurred multiple times according AppCenter.

**Comment by NeuronKarrde** [comment]
As I understand, SplashScreen uses Mvx.Resolve<IMvxAppStart> in several places, fix was made just for one place. One workaround - override RunAppStart in SplashScreen
`protected override void RunAppStart(Bundle bundle)
       {
           if (Mvx.TryResolve<IMvxAppStart>(out IMvxAppStart mvxAppStart))
           {
               if (mvxAppStart.IsStarted)
                   return;
               mvxAppStart.Start(this.GetAppStartHint((object) bundle));
           }
       }`

**Comment by nmilcoff** [comment]
@NeuronKarrde would you mind opening a PR with these changes?

**Comment by NeuronKarrde** [comment]
I haven't permission to push and create PR. How can I get them? Just change from at MvxSplashScreenAppCompatActivity and MvxSplashScreenActivity
`protected virtual async Task RunAppStartAsync(Bundle bundle)
        {
            var startup = Mvx.IoCProvider.Resolve<IMvxAppStart>();
            if (!startup.IsStarted)
                await startup.StartAsync(GetAppStartHint(bundle));
        }`

to
`protected virtual async Task RunAppStartAsync(Bundle bundle)
        {
            if (Mvx.IoCProvider.TryResolve<IMvxAppStart>(out IMvxAppStart startup))
            {
                if (!startup.IsStarted)
                    await startup.StartAsync(GetAppStartHint(bundle));
            }
        }`

Can anybody create this PR?

**Comment by Cheesebaron** [comment]
@NeuronKarrde fork the repository.

**Comment by nmilcoff** [comment]
@martijn00 has something changed that fixes this issue? 🤔

**Comment by vallgrenerik** [comment]
When is 6.2.3 planned to be released @martijn00 ?

**Comment by Cheesebaron** [comment]
@vallgrenerik soon ™️

**Comment by vallgrenerik** [comment]
@Cheesebaron Okey! I reverted to 6.2.0 and it works.
